update 4.2

diff --git a/ndk-gdb b/ndk-gdb
--- a/ndk-gdb
+++ b/ndk-gdb
@@ -24,14 +24,55 @@
 # need to launch ndk-gdb from your application project directory
 # after doing ndk-build && ant install && <start-application-on-device>
 #
-. `dirname $0`/build/core/ndk-common.sh
+PROGDIR=`dirname $0`
+PROGDIR=`cd $PROGDIR && pwd`
+
+# Check if absolute NDK path contain space
+#
+case $PROGDIR in
+    *\ *) echo "ERROR: NDK path cannot contain space"
+          exit 1
+        ;;
+esac
+
+. $PROGDIR/build/core/ndk-common.sh
 
 force_32bit_binaries
 
-find_program ADB_CMD adb
-ADB_FLAGS=
+# Find if a given shell program is available.
+# We need to take care of the fact that the 'which <foo>' command
+# may return either an empty string (Linux) or something like
+# "no <foo> in ..." (Darwin). Also, we need to redirect stderr
+# to /dev/null for Cygwin
+#
+# $1: program name
+# Out: program path, or empty string
+# Return: 0 on success, != 0 on error
+#
+find_program ()
+{
+    local PROG RET
+    PROG=$(which "$1" 2>/dev/null)
+    RET=$?
+    if [ $RET != 0 ]; then
+        PROG=
+    fi
+    echo "$PROG"
+    return $RET
+}
 
-AWK_CMD=awk
+quote_spaces ()
+{
+    echo "$@" | sed -e 's! !\ !g'
+}
+
+# If ADB_CMD is not defined, try to find a program named 'adb'
+# in our path.
+ADB_CMD=${ADB_CMD:-$(find_program adb)}
+ADB_FLAGS=${ADB_FLAGS:-}
+DEVICE_SERIAL=
+
+AWK_CMD=${AWK_CMD:-$(find_program awk)}
 
 DEBUG_PORT=5039
 
@@ -72,7 +113,7 @@ get_build_var ()
     if [ -z "$GNUMAKE" ] ; then
         GNUMAKE=make
     fi
-    $GNUMAKE --no-print-dir -f $ANDROID_NDK_ROOT/build/core/build-local.mk -C $PROJECT DUMP_$1
+    $GNUMAKE --no-print-dir -f $ANDROID_NDK_ROOT/build/core/build-local.mk -C $PROJECT DUMP_$1 | tail -1
 }
 
 get_build_var_for_abi ()
@@ -80,7 +121,7 @@ get_build_var_for_abi ()
     if [ -z "$GNUMAKE" ] ; then
         GNUMAKE=make
     fi
-    $GNUMAKE --no-print-dir -f $ANDROID_NDK_ROOT/build/core/build-local.mk -C $PROJECT DUMP_$1 APP_ABI=$2
+    $GNUMAKE --no-print-dir -f $ANDROID_NDK_ROOT/build/core/build-local.mk -C $PROJECT DUMP_$1 APP_ABI=$2 | tail -1
 }
 
 # Used to run an awk script on the manifest
@@ -109,6 +150,26 @@ native_path ()
 }
 fi # HOST_OS != windows
 
+# We need to ensure the ANDROID_NDK_ROOT is absolute, otherwise calls
+# to get_build_var, get_build_var_for_abi and run_awk_manifest_script
+# might fail, e.g. when invoked with:
+#
+#   cd $NDKROOT
+#   ./ndk-gdb --project=/path/to/project
+#
+path_is_absolute ()
+{
+    local P P2
+    P=$1       # copy path
+    P2=${P#/}  # remove / prefix, if any
+    [ "$P" != "$P2" ]
+}
+
+if ! path_is_absolute "$ANDROID_NDK_ROOT"; then
+    ANDROID_NDK_ROOT=$(pwd)/$ANDROID_NDK_ROOT
+fi
+
+
 VERBOSE=no
 while [ -n "$1" ]; do
     opt="$1"
@@ -123,13 +184,15 @@ while [ -n "$1" ]; do
         -s)
             check_parameter $1 $2
             check_adb_flags
-            ADB_FLAGS=" -s $2"
+            ADB_FLAGS=" -s"
+            DEVICE_SERIAL=$2
             shift
             ;;
         -s*)
             check_adb_flags
             optarg=`expr -- "$opt" : '-s\(.*\)'`
-            ADB_FLAGS=" -s $optarg"
+            ADB_FLAGS=" -s"
+            DEVICE_SERIAL=$optarg
             ;;
         -p)
             check_parameter $1 $2
@@ -246,7 +309,7 @@ fi
 
 # Check ADB tool version
 if [ -n "$OPTION_ADB" ] ; then
-    ADB_CMD="$OPTION_ADB"
+    ADB_CMD=$OPTION_ADB
     log "Using specific adb command: $ADB_CMD"
 else
     if [ -z "$ADB_CMD" ] ; then
@@ -258,24 +321,89 @@ else
     log "Using default adb command: $ADB_CMD"
 fi
 
-ADB_VERSION=`$ADB_CMD version`
+ADB_CMD=$(quote_spaces $ADB_CMD)
+ADB_VERSION=$("$ADB_CMD" version 2>/dev/null)
 if [ $? != 0 ] ; then
     echo "ERROR: Could not run ADB with: $ADB_CMD"
     exit 1
 fi
 log "ADB version found: $ADB_VERSION"
 
-ADB_CMD="${ADB_CMD}${ADB_FLAGS}"
-log "Using final ADB command: '$ADB_CMD'"
+if [ "x$DEVICE_SERIAL" = "x" ]; then
+    log "Using ADB flags: $ADB_FLAGS"
+else
+    log "Using ADB flags: $ADB_FLAGS" \"$DEVICE_SERIAL\"
+fi
 
-adb_shell ()
+# Run an ADB command with the right ADB flags
+# $1+: adb command parameter
+adb_cmd ()
 {
-    # Run an adb shell command and return its output.
-    #
-    # We need to filter weird control characters like \r that are
-    # included in the output.
-    #
-    $ADB_CMD shell $@ | sed -e 's![[:cntrl:]]!!g'
+    if [ "x$DEVICE_SERIAL" = "x" ]; then
+        "$ADB_CMD" $ADB_FLAGS "$@"
+    else
+        # NOTE: We escape $ADB_CMD and $DEVICE_SERIAL in case they contains spaces.
+        "$ADB_CMD" $ADB_FLAGS "$DEVICE_SERIAL" "$@"
+    fi
+}
+
+# Used internally by adb_var_shell and adb_var_shell2.
+# $1: 1 to redirect stderr to $1, 0 otherwise.
+# $2: Variable name that will contain the result
+# $3+: Command options
+_adb_var_shell ()
+{
+    # We need a temporary file to store the output of our command
+    local CMD_OUT RET OUTPUT VARNAME REDIRECT_STDERR
+    REDIRECT_STDERR=$1
+    VARNAME=$2
+    shift; shift;
+    CMD_OUT=`mktemp /tmp/ndk-gdb-cmdout-XXXXXX`
+    # Run the command, while storing the standard output to CMD_OUT
+    # and appending the exit code as the last line.
+    if [ "$REDIRECT_STDERR" != 0 ]; then
+        adb_cmd shell "$@" ";" echo \$? | sed -e 's![[:cntrl:]]!!g' > $CMD_OUT 2>&1
+    else
+        adb_cmd shell "$@" ";" echo \$? | sed -e 's![[:cntrl:]]!!g' > $CMD_OUT
+    fi
+    # Get last line in log, which contains the exit code from the command
+    RET=`sed -e '$!d' $CMD_OUT`
+    # Get output, which corresponds to everything except the last line
+    OUT=`sed -e '$d' $CMD_OUT`
+    rm -f $CMD_OUT
+    eval $VARNAME=\"\$OUT\"
+    return $RET
+}
+
+# Run a command through 'adb shell' and captures its standard output
+# into a variable. The function's exit code is the same than the command's.
+#
+# This is required because there is a bug where "adb shell" always returns
+# 0 on the host, even if the command fails on the device.
+#
+# $1: Variable name (e.g. FOO)
+# On exit, $FOO is set to the command's standard output
+#
+# The return status will be 0 (success) if the command succeeded
+# or 1 (failure) otherwise.
+adb_var_shell ()
+{
+    _adb_var_shell 0 "$@"
+}
+
+# A variant of adb_var_shell that stores both stdout and stderr in the output
+# $1: Variable name
+adb_var_shell2 ()
+{
+    _adb_var_shell 1 "$@"
+}
+
+# Return the PID of a given package or program, or 0 if it doesn't run
+# $1: Package name ("com.example.hellojni") or program name ("/lib/gdbserver")
+# Out: PID number, or 0 if not running
+get_pid_of ()
+{
+    adb_cmd shell ps | $AWK_CMD -f $AWK_SCRIPTS/extract-pid.awk -v PACKAGE="$1"
 }
 
 # Check the awk tool
@@ -345,10 +473,17 @@ if [ "$OPTION_LAUNCH_LIST" = "yes" ] ; then
 fi
 
 APP_ABIS=`get_build_var APP_ABI`
+if [ "$APP_ABIS" != "${APP_ABIS%%all*}" ] ; then
+# replace first "all" with all available ABIs
+  ALL_ABIS=`get_build_var NDK_ALL_ABIS`
+  APP_ABIS_FRONT="${APP_ABIS%%all*}"
+  APP_ABIS_BACK="${APP_ABIS#*all}"
+  APP_ABIS="${APP_ABIS_FRONT}${ALL_ABIS}${APP_ABIS_BACK}"
+fi
 log "ABIs targetted by application: $APP_ABIS"
 
 # Check the ADB command, and that we can connect to the device/emulator
-ADB_TEST=`$ADB_CMD shell ls`
+ADB_TEST=`adb_cmd shell ls`
 if [ $? != 0 ] ; then
     echo "ERROR: Could not connect to device or emulator!"
     echo "       Please check that an emulator is running or a device is connected"
@@ -359,7 +494,7 @@ fi
 
 # Check that the device is running Froyo (API Level 8) or higher
 #
-API_LEVEL=`adb_shell getprop ro.build.version.sdk`
+adb_var_shell API_LEVEL getprop ro.build.version.sdk
 if [ $? != 0 -o -z "$API_LEVEL" ] ; then
     echo "ERROR: Could not find target device's supported API level!"
     echo "ndk-gdb will only work if your device is running Android 2.2 or higher."
@@ -376,38 +511,41 @@ fi
 # And check that they are supported by the application
 #
 COMPAT_ABI=none
-CPU_ABI=`adb_shell getprop ro.product.cpu.abi`
-for ABI in $APP_ABIS; do
-    if [ "$ABI" = "$CPU_ABI" ] ; then
+adb_var_shell CPU_ABI1 getprop ro.product.cpu.abi
+adb_var_shell CPU_ABI2 getprop ro.product.cpu.abi2
+
+# Both CPU_ABI1 and CPU_ABI2 may contain multiple comma-delimited abis.
+# Concatanate CPU_ABI1 and CPU_ABI2 and replace all ',' with space.
+# Add trailing space to ease whole-word matching of APP_ABI.
+CPU_ABIS="$CPU_ABI1,$CPU_ABI2"
+CPU_ABIS=$(echo $CPU_ABIS | tr ',' ' ')
+log "Device CPU ABIs: $CPU_ABIS"
+
+APP_ABIS=$APP_ABIS" "
+for CPU_ABI in $CPU_ABIS; do
+    if [ "$APP_ABIS" != "${APP_ABIS%$CPU_ABI *}" ] ; then
         COMPAT_ABI=$CPU_ABI
         break
     fi
 done
 
-CPU_ABI2=`adb_shell getprop ro.product.cpu.abi2`
-if [ -z "$CPU_ABI2" ] ; then
-    log "Device CPU ABI: $CPU_ABI"
-else
-    log "Device CPU ABIs: $CPU_ABI $CPU_ABI2"
-    if [ "$COMPAT_ABI" = "none" ] ; then
-        for ABI in $APP_ABIS; do
-            if [ "$ABI" = "$CPU_ABI2" ] ; then
-                COMPAT_ABI=$CPU_ABI2
-                break
-            fi
-        done
-    fi
-fi
 if [ "$COMPAT_ABI" = none ] ; then
     echo "ERROR: The device does not support the application's targetted CPU ABIs!"
-    if [ "$CPU_ABI2" = "$CPU_ABI" ] ; then
-        CPU_ABI2=
-    fi
-    echo "       Device supports:  $CPU_ABI $CPU_ABI2"
+    echo "       Device supports:  $CPU_ABIS"
     echo "       Package supports: $APP_ABIS"
     exit 1
 fi
 log "Compatible device ABI: $COMPAT_ABI"
+
+# Get information from the build system
+GDBSETUP_INIT=`get_build_var_for_abi NDK_APP_GDBSETUP $COMPAT_ABI`
+log "Using gdb setup init: $GDBSETUP_INIT"
+
+TOOLCHAIN_PREFIX=`get_build_var_for_abi TOOLCHAIN_PREFIX $COMPAT_ABI`
+log "Using toolchain prefix: $TOOLCHAIN_PREFIX"
+
+APP_OUT=`get_build_var_for_abi TARGET_OUT $COMPAT_ABI`
+log "Using app out directory: $APP_OUT"
 
 # Check that the application is debuggable, or nothing will work
 DEBUGGABLE=`run_awk_manifest_script extract-debuggable.awk`
@@ -445,32 +583,22 @@ fi
 # Let's check that 'gdbserver' is properly installed on the device too. If this
 # is not the case, the user didn't install the proper package after rebuilding.
 #
-DEVICE_GDBSERVER=`adb_shell ls /data/data/$PACKAGE_NAME/lib/gdbserver`
-log "Found device gdbserver: $DEVICE_GDBSERVER"
-if pattern_match "No such file or directory" "$DEVICE_GDBSERVER" ] ; then
+adb_var_shell2 DEVICE_GDBSERVER ls /data/data/$PACKAGE_NAME/lib/gdbserver
+if [ $? != 0 ]; then
     echo "ERROR: Non-debuggable application installed on the target device."
     echo "       Please re-install the debuggable version!"
     exit 1
 fi
-
-# Get information from the build system
-GDBSETUP_INIT=`get_build_var_for_abi NDK_APP_GDBSETUP $COMPAT_ABI`
-log "Using gdb setup init: $GDBSETUP_INIT"
-
-TOOLCHAIN_PREFIX=`get_build_var_for_abi TOOLCHAIN_PREFIX $COMPAT_ABI`
-log "Using toolchain prefix: $TOOLCHAIN_PREFIX"
-
-APP_OUT=`get_build_var_for_abi TARGET_OUT $COMPAT_ABI`
-log "Using app out directory: $APP_OUT"
+log "Found device gdbserver: $DEVICE_GDBSERVER"
 
 # Find the <dataDir> of the package on the device
-DATA_DIR=`adb_shell run-as $PACKAGE_NAME /system/bin/sh -c pwd`
-log "Found data directory: '$DATA_DIR'"
+adb_var_shell2 DATA_DIR run-as $PACKAGE_NAME /system/bin/sh -c pwd
 if [ $? != 0 -o -z "$DATA_DIR" ] ; then
     echo "ERROR: Could not extract package's data directory. Are you sure that"
     echo "       your installed application is debuggable?"
     exit 1
 fi
+log "Found data directory: '$DATA_DIR'"
 
 # Launch the activity if needed
 if [ "$OPTION_START" = "yes" ] ; then
@@ -496,7 +624,7 @@ fi
 
 if [ -n "$OPTION_LAUNCH" ] ; then
     log "Launching activity: $PACKAGE_NAME/$OPTION_LAUNCH"
-    run $ADB_CMD shell am start -n $PACKAGE_NAME/$OPTION_LAUNCH
+    run adb_cmd shell am start -n $PACKAGE_NAME/$OPTION_LAUNCH
     if [ $? != 0 ] ; then
         echo "ERROR: Could not launch specified activity: $OPTION_LAUNCH"
         echo "       Use --launch-list to dump a list of valid values."
@@ -504,11 +632,11 @@ if [ -n "$OPTION_LAUNCH" ] ; then
     fi
     # Sleep a bit, it sometimes take one second to start properly
     # Note that we use the 'sleep' command on the device here.
-    run $ADB_CMD shell sleep $DELAY
+    run adb_cmd shell sleep $DELAY
 fi
 
 # Find the PID of the application being run
-PID=`$ADB_CMD shell ps | $AWK_CMD -f $AWK_SCRIPTS/extract-pid.awk -v PACKAGE=$PACKAGE_NAME`
+PID=$(get_pid_of "$PACKAGE_NAME")
 log "Found running PID: $PID"
 if [ $? != 0 -o "$PID" = "0" ] ; then
     echo "ERROR: Could not extract PID of application on device/emulator."
@@ -527,22 +655,19 @@ if [ $? != 0 -o "$PID" = "0" ] ; then
 fi
 
 # Check that there is no other instance of gdbserver running
-GDBSERVER_PS=`$ADB_CMD shell ps | grep lib/gdbserver`
-if [ -n "$GDBSERVER_PS" ] ; then
+GDBSERVER_PID=$(get_pid_of lib/gdbserver)
+if [ "$GDBSERVER_PID" != "0" ]; then
     if [ "$OPTION_FORCE" = "no" ] ; then
         echo "ERROR: Another debug session running, Use --force to kill it."
         exit 1
     fi
     log "Killing existing debugging session"
-    GDBSERVER_PID=`echo $GDBSERVER_PS | $AWK_CMD -f $AWK_SCRIPTS/extract-pid.awk -v PACKAGE=lib/gdbserver`
-    if [ $GDBSERVER_PID != 0 ] ; then
-        run $ADB_CMD shell kill -9 $GDBSERVER_PID
-    fi
+    run adb_cmd shell kill -9 $GDBSERVER_PID
 fi
 
 # Launch gdbserver now
 DEBUG_SOCKET=debug-socket
-run $ADB_CMD shell run-as $PACKAGE_NAME lib/gdbserver +$DEBUG_SOCKET --attach $PID &
+run adb_cmd shell run-as $PACKAGE_NAME lib/gdbserver +$DEBUG_SOCKET --attach $PID &
 if [ $? != 0 ] ; then
     echo "ERROR: Could not launch gdbserver on the device?"
     exit 1
@@ -551,7 +676,7 @@ log "Launched gdbserver succesfully."
 
 # Setup network redirection
 log "Setup network redirection"
-run $ADB_CMD forward tcp:$DEBUG_PORT localfilesystem:$DATA_DIR/$DEBUG_SOCKET
+run adb_cmd forward tcp:$DEBUG_PORT localfilesystem:$DATA_DIR/$DEBUG_SOCKET
 if [ $? != 0 ] ; then
     echo "ERROR: Could not setup network redirection to gdbserver?"
     echo "       Maybe using --port=<port> to use a different TCP port might help?"
@@ -560,10 +685,13 @@ fi
 
 # Get the app_server binary from the device
 APP_PROCESS=$APP_OUT/app_process
-run $ADB_CMD pull /system/bin/app_process `native_path $APP_PROCESS`
+run adb_cmd pull /system/bin/app_process `native_path $APP_PROCESS`
 log "Pulled app_process from device/emulator."
 
-run $ADB_CMD pull /system/lib/libc.so `native_path $APP_OUT/libc.so`
+run adb_cmd pull /system/bin/linker `native_path $APP_OUT/linker`
+log "Pulled linker from device/emulator."
+
+run adb_cmd pull /system/lib/libc.so `native_path $APP_OUT/libc.so`
 log "Pulled libc.so from device/emulator."
 
 # Now launch the appropriate gdb client with the right init commands
